### ISSUE TITLE
Game crashes at the end of preload

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [UnlikePaladin/paladin-furniture-mod#105]
### Bug Description

when loading the game, it reaches the end of the forge preload and crashes.

### Reproduction Steps

**MODLIST:**
Tropicraft-9.6.3.jar                         
transmog-forge-1.2.4+1.20.jar  
supermartijn642configlib-1.1.8-forge-mc1.20.jar   
Create-Dreams-n-Desires-1.20.1-0.2c.PREBETA.jar 
geckolib-forge-1.20.1-4.4.2.jar          
createdeco-2.0.1-1.20.1-forge.jar
2.0.1-1.20.1-forge 
beautify-2.0.2.jar                               
 aether-1.20.1-1.2.0-neoforge.jar              
Architects-Palette-1.20.1-1.3.6.1.jar          
map_atlases-1.20-6.0.2.jar              
mcw-windows-2.2.1-mc1.20.1forge.jar          
Incendium_1.20.4_v5.3.4.jar                
mmersive_weathering-1.20.1-2.0.1-forge.jar  
ForgeEndertech-1.20.1-11.1.0.1-build.0289.jar          
mcw-paintings-1.0.5-1.20.1forge.jar               
Clumps-forge-1.20.1-12.0.0.3.jar              
Controlling-forge-1.20.1-12.0.2.jar         
integrated_api-1.3.7+1.20.1-forge.jar    
YungsApi-1.20-Forge-4.0.4.jar             
Decorative Blocks-forge-1.20.1-4.0.2.jar      
mixinextras-forge-0.2.0-beta.9.jar   
Twigs-1.20.1-3.1.0.jar               
we_addon-1.5.jar                               
mahoutsukai-1.20.1-v1.34.61.jar        
Steam_Rails-1.5.3+forge-mc1.20.1.jar          
Display Case-forge-1.20-1.0.8.jar                 
interiors-0.5.2+mc1.20.1-FORGE.jar              
cloth-config-11.1.118-forge.jar         
sound-physics-remastered-forge-1.20.1-1.3.1.jar         
forge-1.20.1-47.2.0-universal.jar          
paladin-furniture-mod-1.2.0-forge-mc1.20.1.jar
twilightforest-1.20.1-4.3.2145-universal.jar  
athena-forge-1.20.1-3.1.1.jar                    
dsbg-1.0-1.20.1.jar                
idas_forge-1.8.4+1.20.1.jar         
Chipped-forge-1.20.1-3.0.4.jar       
client-1.20.1-20230612.114412-srg.jar       
FarmersDelight-1.20.1-1.2.4.jar       
handcrafted-forge-1.20.1-3.0.6.jar           
Amplified_Nether_1.20.4_v1.2.4.jar      
TerraBlender-forge-1.20.1-3.0.1.4.jar            
moonlight-1.20-2.10.10-forge.jar       
MouseTweaks-forge-mc1.20-2.25.jar               
mixinsquared-forge-0.1.1.jar                       
Jade-1.20.1-forge-11.7.1.jar       
forbidden_arcanus-1.20.1-2.2.4.jar         
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar           
movingelevators-1.4.6-forge-mc1.20.1.jar                   
nethersdelight-1.20.1-4.0.jar               
aeroblender-1.20.1-1.0.1-neoforge.jar   
kffmod-4.10.0.jar                  
trimeffects-1.1.1-forge.jar    
flywheel-forge-1.20.1-0.6.10-7.jar     
create-1.20.1-0.5.1.f.jar  
sootychimneys-1.20.1-1.2.1.jar      
curios-forge-5.3.5+1.20.1.jar          
integrated_stronghold-1.1.0+1.20.1-forge.jar    
Searchables-forge-1.20.1-1.0.2.jar         
Zeta-1.0-13.jar                      
Quark-4.0-436.jar          
supplementaries-1.20-2.8.4.jar  
suppsquared-1.20-1.1.14.jar            
immersive_paintings-0.6.7+1.20.1-forge.jar  
FramedBlocks-9.2.0.jar     
betterarcheology-1.1.6-1.20.1.jar    
buildersaddition-1.20.1-20230928a.jar     
resourcefullib-forge-1.20.1-2.1.23.jar               
worldedit-mod-7.2.15.jar      
extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar       
cumulus_menus-1.20.1-1.0.0-neoforge.jar       
cfm-forge-1.20.1-7.0.0-pre36.jar                 
architectury-9.2.14-forge.jar     
dimdoors-5.3.0-forge-beta1.jar   
Adorn-5.0.1+1.20.1-forge.jar    
niftyblocks-1.31.jar  
The_Undergarden-1.20.1-0.8.13.jar   
AdChimneys-1.20.1-10.1.4.0-build.0314.jar      
nitrogen_internals-1.20.1-1.0.2-neoforge.jar
the_bumblezone-7.2.15+1.20.1-forge.jar
deep_aether-1.20.1-1.0.2.jar                
valhelsia_core-forge-1.20.1-1.1.1.jar

### Log File

[latest.log](https://github.com/UnlikePaladin/paladins-furniture/files/14467930/latest.log)

**Comment by UnlikePaladin** [comment]
Hi this is actually not an issue with my mod, but an issue with another of your mods, specifically one of the ones that says Create, not sure if it's Create-Dreams or createdeco, but one of those two failed to initialize so my mod crashed when it tried to load later, I literally released 1.2.1 today which will make that more clear and fix this problem where my mod crashes later and thus is blamed, but CurseForge is working on reviewing it so you can download it from [Modrinth](https://modrinth.com/mod/paladins-furniture) until then, look at the lines 
`[20:29:12] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: create, class com.simibubi.create.Create
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23304!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23303!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	at com.rabbitminers.extendedgears.registry.forge.ExtendedCogwheelsCreativeModeTabsImpl.useBaseTab(ExtendedCogwheelsCreativeModeTabsImpl.java:52) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsCreativeModeTabs.useBaseTab(ExtendedCogwheelsCreativeModeTabs.java) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:37) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.simibubi.create.AllBlocks.redirect$bpk000$changeLayerType(AllBlocks.java:2424) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:354) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.Create.onCtor(Create.java:108) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.Create.<init>(Create.java:93) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	... 14 more
[20:29:12] [modloading-worker-0/INFO]: Initializing TerraBlender underground biome compat
[20:29:12] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: railways, class com.railwayteam.railways.forge.RailwaysImpl
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23304!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23303!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.simibubi.create.AllBlocks
	at com.simibubi.create.AllBogeyStyles.<clinit>(AllBogeyStyles.java:42) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.AllBogeyStyles$BogeyStyleBuilder.build(AllBogeyStyles.java:126) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.railwayteam.railways.registry.CRBogeyStyles.<clinit>(CRBogeyStyles.java:110) ~[Steam_Rails-1.5.3+forge-mc1.20.1.jar%23284!/:?]
	at com.railwayteam.railways.ModSetup.register(ModSetup.java:23) ~[Steam_Rails-1.5.3+forge-mc1.20.1.jar%23284!/:?]
	at com.railwayteam.railways.Railways.init(Railways.java:78) ~[Steam_Rails-1.5.3+forge-mc1.20.1.jar%23284!/:?]
	at com.railwayteam.railways.forge.RailwaysImpl.<init>(RailwaysImpl.java:36) ~[Steam_Rails-1.5.3+forge-mc1.20.1.jar%23284!/:?]
	... 14 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)' [in thread "modloading-worker-0"]
	at com.rabbitminers.extendedgears.registry.forge.ExtendedCogwheelsCreativeModeTabsImpl.useBaseTab(ExtendedCogwheelsCreativeModeTabsImpl.java:52) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsCreativeModeTabs.useBaseTab(ExtendedCogwheelsCreativeModeTabs.java) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:37) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.simibubi.create.AllBlocks.redirect$bpk000$changeLayerType(AllBlocks.java:2424) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:354) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.Create.onCtor(Create.java:108) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.Create.<init>(Create.java:93) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	... 14 more
[20:29:12] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: extendedgears, class com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23304!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23303!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks
	at com.rabbitminers.extendedgears.ExtendedCogwheels.init(ExtendedCogwheels.java:33) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge.<init>(ExtendedCogwheelsForge.java:24) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	... 14 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)' [in thread "modloading-worker-0"]
	at com.rabbitminers.extendedgears.registry.forge.ExtendedCogwheelsCreativeModeTabsImpl.useBaseTab(ExtendedCogwheelsCreativeModeTabsImpl.java:52) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsCreativeModeTabs.useBaseTab(ExtendedCogwheelsCreativeModeTabs.java) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:37) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23253!/:?]
	at com.simibubi.create.AllBlocks.redirect$bpk000$changeLayerType(AllBlocks.java:2424) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:354) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.Create.onCtor(Create.java:108) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]
	at com.simibubi.create.Create.<init>(Create.java:93) ~[create-1.20.1-0.5.1.f.jar%23245!/:0.5.1.f]`
