### ISSUE TITLE
Incompatibility: Paladin's Furniture and Cozy Home crash when loaded together (Forge 1.20.1)

### ISSUE THREAD

**Issue by adozenlionsroaring** [UnlikePaladin/paladin-furniture-mod#106]
### Bug Description

There seems to be an incompatibility between Paladin's furniture and the latest version of Lucky's Cozy Home in Minecraft 1.20.1. I tried loading each of these mods individually and was successful; however, when loaded together, they crash. I've provided the log in the pastebin. Of particular relevance are these parts:

-------

"Caused by: java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=blockstate, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{minecraft:air}
		at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%231030!/:?] {re:mixin,pl:connector_pre_launch:A,re:computing_frames,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin from mod ferritecore,pl:mixin:A,pl:connector_pre_launch:A}
		at net.mcreator.cozyhome.block.OakPlankBlock$1.getLightLevel(OakPlankBlock.java:46) ~[Cozy_home-3.0.1-1.20.1.jar%23691!/:?] {re:classloading}
		at net.mcreator.cozyhome.block.OakPlankBlock.lambda$new$0(OakPlankBlock.java:54) ~[Cozy_home-3.0.1-1.20.1.jar%23691!/:?] {re:classloading}
		at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.<init>(BlockBehaviour.java:468) ~[client-1.20.1-20230612.114412-srg.jar%231030!/:?]"

"Suppressed: net.minecraftforge.fml.ModLoadingException: Paladin's Furniture (pfm) encountered an error during the common_setup event phase
§7java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=blockstate, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{minecraft:air}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.20.1-47.2.0.jar%231032!/:?] {}
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:346) ~[fmlcore-1.20.1-47.2.0.jar%231031!/:?] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.0.jar%231031!/:?] {re:mixin}
		at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:344) ~[fmlcore-1.20.1-47.2.0.jar%231031!/:?] {}
		at net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:337) ~[fmlcore-1.20.1-47.2.0.jar%231031!/:?] {}"

--------

I've also notified the owner of the Cozy Home mod - I'm not sure which end it would be easier to fix the problem.

### Reproduction Steps

Load both Paladin's Furniture v1.2.1 and Lucky's Cozy Home v3.0.1 in Forge, Minecraft 1.20.1.

### Log File

http://pastebin.com/uQ9BQtn8

**Comment by adozenlionsroaring** [comment]
Just confirming, this incompatibility between Paladin's Furniture and Lucky's Cozy Home is still present for the version of LCH uploaded on the 18th of March (v3.0.2).
