### ISSUE TITLE
Woodworking table crashes the game

### ISSUE THREAD

**Issue by PlanetOfJupiter** [UnlikePaladin/paladin-furniture-mod#16]
Every time I try to open the woodworking table, 

<details><summary>This is the crash report</summary>

[---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/15/22 4:38 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.recipebook.RecipeBookGui.func_191878_b(RecipeBookGui.java:147) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at mezz.itemzoom.client.RenderHandler.getSpaceOnLeft(RenderHandler.java:108) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at mezz.itemzoom.client.RenderHandler.getRenderingArea(RenderHandler.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at mezz.itemzoom.client.RenderHandler.onItemStackTooltip(RenderHandler.java:66) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at mezz.itemzoom.ItemZoomClient.lambda$setupRenderHandler$6(ItemZoomClient.java:70) ~[?:?] {re:classloading}
	at mezz.itemzoom.ItemZoomClient$$Lambda$35584/1086244764.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3224/1039634839.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3872/439190664.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:443) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:422) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:397) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.renderWrappedToolTip(Screen.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230457_a_(Screen.java:118) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230459_a_(ContainerScreen.java:164) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:highlighter.mixins.json:ContainerScreenMixin,pl:mixin:APP:mixins.ipnext.json:MixinAbstractContainerScreen,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.unlikepaladin.pfm.client.screens.WorkbenchScreen.func_230430_a_(WorkbenchScreen.java:47) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:363) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:356) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$501/1517223475.call(Unknown Source) [forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.recipebook.RecipeBookGui.func_191878_b(RecipeBookGui.java:147) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at mezz.itemzoom.client.RenderHandler.getSpaceOnLeft(RenderHandler.java:108) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at mezz.itemzoom.client.RenderHandler.getRenderingArea(RenderHandler.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at mezz.itemzoom.client.RenderHandler.onItemStackTooltip(RenderHandler.java:66) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at mezz.itemzoom.ItemZoomClient.lambda$setupRenderHandler$6(ItemZoomClient.java:70) ~[?:?] {re:classloading}
	at mezz.itemzoom.ItemZoomClient$$Lambda$35584/1086244764.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3224/1039634839.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3872/439190664.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:443) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:422) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:397) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.renderWrappedToolTip(Screen.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230457_a_(Screen.java:118) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230459_a_(ContainerScreen.java:164) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:highlighter.mixins.json:ContainerScreenMixin,pl:mixin:APP:mixins.ipnext.json:MixinAbstractContainerScreen,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.unlikepaladin.pfm.client.screens.WorkbenchScreen.func_230430_a_(WorkbenchScreen.java:47) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:363) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:356) ~[?:?] {re:classloading,re:mixin}
-- Screen render details --
Details:
	Screen name: com.unlikepaladin.pfm.client.screens.WorkbenchScreen
	Mouse location: Scaled: (480, 270). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['PlanetOfJupiter'/138, l='ClientLevel', x=-227.46, y=59.00, z=362.90]]
	Chunk stats: Client Chunk Cache: 4096, 1444
	Level dimension: minecraft:overworld
	Level spawn location: World: (121,129,234), Chunk: (at 9,8,10 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2058586 game time, 1023655 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$501/1517223475.call(Unknown Source) [forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3380387280 bytes (3223 MB) / 9040822272 bytes (8622 MB) up to 9455009792 bytes (9017 MB)
	CPUs: 16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10144m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	
	Crash Report UUID: aea4b858-b591-4745-ba1a-a777a504ba1a
	FramedBlocks BlockEntity Warning: Not applicable
	Kiwi Modules: 
		
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Loaded Shaderpack: ComplementaryShaders_v4.4.zip
		Profile: Custom (+29 options changed by user)
	NEC status: No NEC detected
	Launched Version: forge-36.2.35
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.98, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, inspirations:config_resources (incompatible), quark:emote_resources (incompatible), file/Spartan Retextured.zip, file/FreshAnimations_v1.3.zip, file/VanillaTweaks_r301353.zip, file/Create Style Vanilla+Modded v10 [1.16].zip, file/Crops-3D_MC1.16.5_v1.0.0.zip, file/Specular + Normal Vanilla.zip, file/xali's Potions v1.0.zip (incompatible), file/Better-Leaves-7.0-1.13+.zip (incompatible), file/Fantasy_Ores_Modded[v1.8].zip (incompatible), file/Fantasy_Ores_v6_shiny_ores.zip (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor ]

</details>

I am running 272 mods, 
<details><summary>mods list</summary>

[Decorative Blocks modded compat (by Evo_934)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
The Endergetic Expansion (by TeamAbnormals)
Thermal Innovation (by TeamCoFH)
Hexerei (by JoeFoxe)
Xaero's Minimap (by xaero96)
Better Normal + Specular Textures (by gfdsikmgfdsigfdsfgd)
Immersive Petroleum (by Flaxbeard)
Configured (by MrCrayfish)
Create Stuff & Additions (by Furti_Two)
[Optifine] Animated RGB GUI (by CrisXolt)
Framed Compacting Drawers (by Eutropium)
Dungeons Libraries (by Patrigan)
Spartan Weaponry (by ObliviousSpartan)
Item Filters (by LatvianModder)
I Like Wood - Oh The Biomes You'll Go Plugin (by yamahari_)
Waystones (by BlayTheNinth)
Supplementaries (by MehVahdJukaar)
TerraForged (by won_ton_)
Dynamic Surroundings (by OreCruncher)
Alex's Mobs (by sbom_xela)
Motschen's Better Leaves (by Motschen)
Trading Post (by Fuzs_)
I Like Wood (by yamahari_)
Blur (by tterrag1098)
Botania (by Vazkii)
Better Third Person (by Socolio)
Create Crafts & Additions (by MRHminer)
More Axolotl Variants Mod (C&C Backport Add-On) (by AkashiiKun69)
Kotlin for Forge (by thedarkcolour)
Paladin's Furniture (by UnlikePaladin)
Display Case (by ChappiePie)
Traveler's Titles (Forge) (by YUNGNICKYOUNG)
ExpandAbility (by florensie)
Durability Tooltip (by SuperMartijn642)
Ore Variants (by IcyCrystaI)
FerriteCore (Forge) (by malte0811)
Creatures and Beasts (by joosh_7889)
Jade 🔍 (by Snownee_)
Runelic (by DarkhaxDev)
Create Style Modded Compats (by wedge1453)
Adorn (Forge) (by Juicebus)
Natural Decor Mod (by marioz170)
AutoRegLib (by Vazkii)
Just Enough Items (JEI) (by mezz)
Create Cafe (by 1mphuls3)
Savage & Ravage (by TeamAbnormals)
Create Deco (by talrey)
EnderChests (by ShetiPhian)
ChineseWorkshop (by cityofskytcd)
ShetiPhianCore (by ShetiPhian)
xali's Bushy Leaves (by xalixilax)
Simple Voice Chat (by henkelmax)
Mouse Tweaks (by YaLTeR)
Buzzier Bees (by TeamAbnormals)
Just Zoom [Forge] (by Keksuccino)
[Fabric/Forge] Market Crates (1.15 to 1.19) (by lfaoanl)
Alex's Delight (by NCP_Bails)
Bookshelf (by DarkhaxDev)
Bamboo Blocks (by TeamAbnormals)
Macaw's Trapdoors (by sketch_macaw)
libIPN (by mirinimi)
XP Tome (by bl4ckscor3)
Psi (by Vazkii)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
Remove Potions Icons (by 00theblackwolf00)
Just Enough Professions (JEP) (by Mrbysco)
Spartan Weaponry: Twilight Forest (by kreloxcz)
YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
Blueprint (by TeamAbnormals)
Quark Oddities (by Vazkii)
AppleSkin (by squeek502)
Bettas Delight (A Farmer's Delight Add-on) (by nocubeyt)
Inventory Pets (by Purplicious_Cow_)
Entity Culling Fabric/Forge (by tr9zw)
Variant16x (by BKthousand)
Macaw's Windows (by sketch_macaw)
Collective (Forge) (by Serilum)
Dungeons Plus (by ModdingLegacy)
Create Plus (by Robocraft999)
ConnectedTexturesMod (by tterrag1098)
Mushroom Quest (by Ryukusu)
Simple Shops (by wolforce)
Cyclic (by Lothrazar)
Oh The Biomes You'll Go (by AOCAWOL)
Gauges and Switches (by wilechaote)
End Remastered (by jack_bagel)
Macaw's Paintings (by sketch_macaw)
Konkrete [Forge] (by Keksuccino)
Iceberg [Forge] (by Grend_G)
Thermal Locomotion (by TeamCoFH)
Spartan Shields (by ObliviousSpartan)
Just Enough Resources (JER) (by way2muchnoise)
CaveBiomeAPI [Forge] (by blackgear27)
Turtlemancy (by alienpatois)
BetterEnd Reforked (by someoneelsewastaken)
Create (by simibubi)
FTB Quests (Forge) (by FTB)
Enchantment Descriptions (by DarkhaxDev)
Mekanism (by bradyaidanc)
Twilight Delight (by laokuai233)
Environmental (by TeamAbnormals)
Inspirations (by KnightMiner)
Cozy Comforts (by Season_Cookie)
Simple Storage Network (by Lothrazar)
Item Highlighter [Forge] (by Grend_G)
Macaw's Lights and Lamps (by sketch_macaw)
ApexCore (by ApexMdr)
Immersive Engineering (by BluSunrize)
Caves & Cliffs Backport (by blackgear27)
Rubidium (by Asek3)
Fog Overrides [Forge] (by fabbe50)
Fantasy Ores Modded by CesarZorak (by cesar_zorak)
CoFH Core (by TeamCoFH)
MrCrayfish's More Furniture Mod (by MrCrayfish)
Tetra (by mickelus)
Improved Backpacks (by DreenDexTwitch)
Fox's Handheld Cannon (by foxinthebox__)
SecretRoomsMod (by AbrarSyed)
Waxed Wood (by stephenb6174)
Fantasy Ores by CesarZorak (by cesar_zorak)
BetterEnd (Forge) (by Beethoven92)
BetterF3 (by cominixo)
Macaw's Roofs - Oh The Biomes You'll Go (by Samlegamer_)
Upgrade Aquatic (by TeamAbnormals)
Large Meals (An Add-on for Farmer's Delight) (by LostWiz08)
Rhino (by LatvianModder)
FTB Library (Forge) (by FTB)
Neapolitan (by TeamAbnormals)
Macaw's Fences and Walls (by sketch_macaw)
Paragliders (by Tictim)
The Twilight Forest (by Benimatic)
PlayerEx (by clevernucleus)
Thermal Innovation Cyclic Compat (by Aezshma)
Traveler's Backpack (by Tiviacz1337)
Crafting Tweaks (by BlayTheNinth)
Baby Fat (by fusionstudiomc)
Biomes O' Plenty (by Forstride)
Antique Atlas (by Hunternif)
Caves & Cliffs Backport (Additions) (by jukittita)
Rev's Better Structures (by renatogloe)
Connected Glass (by SuperMartijn642)
Fairy Lights (by pau101)
Guard Villagers (by almightytallestred)
Skinned Lanterns (Forge) (by nuxthefox)
Kiwi 🥝 (Forge) (by Snownee_)
Registrator (by ApexMdr)
iChunUtil (by ohaiiChun)
KubeJS (by LatvianModder)
Citadel (by sbom_xela)
Tips (by DarkhaxDev)
Chipped (by terrariumearth)
Darker Depths (by naterbobber)
Xaero's World Map (by xaero96)
Valhelsia Structures (by ValhelsiaTeam)
Quark (by Vazkii)
Chimes (by BlewberryPie)
Inventory Profiles Next (by mirinimi)
ItemZoom (by mezz)
Macaw's Doors (by sketch_macaw)
Aquaculture 2 (by Shadowclaimer)
Macaw's Bridges - Abnormals (by Samlegamer_)
Autumnity (by TeamAbnormals)
Back Tools (by ohaiiChun)
Mysterious Mountain Lib (by sz0999312)
Frozen Up (by ninnih_)
Macaw's Roofs (by sketch_macaw)
Visual Workbench (by Fuzs_)
Sky Villages [Forge] (by y4z0n)
Create: Steam Powered (by yuesha_yc)
Druidcraft (by VulpTheHorseDog2)
GottschCore (by gottsch)
Dark Paintings (by DarkhaxDev)
Thermal Cultivation (by TeamCoFH)
Exline's Furniture Mod (by exlinegames)
Structure Gel API (by ModdingLegacy)
FramedBlocks (by XFactHD)
Crops 3D (by NinthWorld)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Backpacked (by MrCrayfish)
A Better GUI 2 (by AstronoCraft)
Architectury API (Fabric/Forge) (by shedaniel)
Cherished Worlds (Forge) (by TheIllusiveC4)
Macaw's Bridges - Biome O' Plenty (by Samlegamer_)
Artifacts (by ochotonida)
Advanced Chimneys (by EnderLanky)
Macaw's Paths and Pavings (by sketch_macaw)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Macaw's Fences - Oh The Biomes You'll Go (by Samlegamer_)
Decorative Winter (by lilypuree)
Macaw's Fences - Biomes O' Plenty (by Samlegamer_)
Moonlight Lib (by MehVahdJukaar)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Enchant With Mob (by bagu_chan500)
Oculus (by Asek3)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Dungeons Mobs (by the_infamous_1)
More Minecarts and Rails (by goldey3)
KubeJS Thermal (by LatvianModder)
Advanced Hook Launchers (by EnderLanky)
Bettas (by fusionstudiomc)
Goblin Traders (by MrCrayfish)
Controlling (by Jaredlll08)
Thermal Expansion (by TeamCoFH)
Macaw's Bridges (by sketch_macaw)
Iron Furnaces [FORGE] (by XenoMustache)
Puzzles Lib (by Fuzs_)
SuperMartijn642's Config Lib (by SuperMartijn642)
Brooms (by EterDelta)
Iron Chests (by ProgWML6)
GeckoLib (by ThanosGecko)
Cloth Config API (Fabric/Forge) (by shedaniel)
Simple Discord Rich Presence (Forge / Fabric) (by Sunekaer)
Extended Creative Inventory (Forge) (by Serilum)
Bedspreads (Forge) (by TheIllusiveC4)
Infernal Expansion (by InfernalStudios)
Better Advancements (by way2muchnoise)
Flywheel (by jozufozu)
Honey Expansion (Add-on for Farmer's Delight) (by Spiteful_raccoon)
Dungeons Gear (by the_infamous_1)
Macaw's Bridges - Oh The Biomes You'll Go (by Samlegamer_)
Nether's Delight (by lumpazl)
Personality (by TeamAbnormals)
Chisel (by tterrag1098)
Clumps (by Jaredlll08)
Farmer's Delight Integration (by iku_tv)
Dark Utilities (by DarkhaxDev)
FTB Teams (Forge) (by FTB)
xali's Enhanced Jungle Wood (by xalixilax)
Boatload (by TeamAbnormals)
Sophisticated Backpacks (by P3pp3rF1y)
Spartan Retextured (by aneckdope)
Farmer's Delight Compats (by burritoeatinghamster)
MrCrayfish's Furniture Mod (by MrCrayfish)
Spiders 2.0 (by TheCyberBrick)
Macaw's Roofs - Biomes O' Plenty (by Samlegamer_)
Decoration and Furniture (Forge) (by Skart2007)
Skin Layers 3D (Fabric/Forge) (by tr9zw)
Drawers Tooltip (by Snownee_)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
Atmospheric (by TeamAbnormals)
Decorative Blocks (by stohun)
GraveStone Mod (by henkelmax)
AstikorCarts [Horse Carts] (by pau101)
Variant16x: Buzzier Bees (by BKthousand)
Bag of Yurting (by Commoble)
Tree Harvester (Forge) (by Serilum)
Fresh Animations (by Fresh__LX)
Untamed Wilds (by raytrace82)
ForgeEndertech (by EnderLanky)
CosmicNPCs (by Namensammler42)
Valhelsia Core (by ValhelsiaTeam)
City Modernities (by Renared_688)
Storage Drawers (by Texelsaur)
Falling Leaves (Forge) (by Cheaterpaul)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Small Ships [Fabric & Forge] (by talhanation)
Cosmetic Armor Reworked (by LainMI)
Mantle (by mDiyo)
mutil (by mickelus)
Ars Nouveau (by baileyholl2)
Quests Additions (Forge) (by NaturaSpell)
Patchouli (by Vazkii)
PneumaticCraft: Repressurized (by desht_08)
I Like Wood - Biomes O' Plenty Plugin (by yamahari_)
Nature's Compass (by Chaosyr)
BetterNether Reforged (by someoneelsewastaken)
Architect's Palette (by Jsburg)
Fantasy's Furniture (by ApexMdr)
Coins JE (by DarkhaxDev)
Cultural Delights (by NCP_Bails)
Farmer's Delight (by vectorwing)
Forbidden and Arcanus (by cesar_zorak)
ToroHealth Damage Indicators (by ToroCraft)
Curios API (Forge) (by TheIllusiveC4)
LoFi Records to Mine To (by aaronhowser1)
Thermal Foundation (by TeamCoFH)
Builders Crafts & Additions (Forge) (by MRHminer)
Create Automated (by kotakotik22)
Farmer's Extra Foods (by Ratatang)
WorldEdit (by sk89q)
Polymorph (Forge) (by TheIllusiveC4)
Create: Alloyed (by MythrilBagels)
xali's Potions (by xalixilax)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
Oh My Gourd (by TeamCoFH)
Buddycards (by wildcard_gamer) ]

</details>
if a file is attached please ignore it, but it's got my configs if it IS attached.

**Comment by UnlikePaladin** [comment]
That is quite concerning, it's crashing because of the recipe book, I set it to be null (not exist) because Mojang hardcodes it and there is no way for modders to modify it but itemzoom seems to be messing with it. I'll look into what I can do. Thanks for the report!

**Comment by PlanetOfJupiter** [comment]
oh I see! Thank you, i'll remove the mod and see if that fixes the issue for now :)
