### ISSUE TITLE
[1.19.4] [1.1.4] [Forge] No crafting recipes on click in JEI on client side

### ISSUE THREAD

**Issue by Cvazer** [UnlikePaladin/paladin-furniture-mod#48]
When in single player - all good. When hosting via "Open to LAN" button - all ok on host side, but no recipes for crafting on click on client side (e. g, for someone who is joining to hosted world). For usage recipes it works everywhere for some reason. The same problem appears when hosting on dedicated server, no craft recipes on click for any players.

Should reproduce on MC 1.19.4 + forge 45.0.64 + JEI 13.1.0.11 no other mods

**Comment by Cvazer** [comment]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.server.IntegratedServer.m_206579_()" because the return value of "net.minecraft.client.Minecraft.m_91092_()" is null
	at com.unlikepaladin.pfm.compat.forge.jei.PaladinFurnitureModJEIPlugin.lambda$static$1(PaladinFurnitureModJEIPlugin.java:37) ~[paladin-furniture-mod-1.1.4-forge-mc1.19.4.jar%23197!/:?] {re:classloading}
	at com.unlikepaladin.pfm.compat.forge.jei.FurnitureCategory.setRecipe(FurnitureCategory.java:63) ~[paladin-furniture-mod-1.1.4-forge-mc1.19.4.jar%23197!/:?] {re:classloading}
	at com.unlikepaladin.pfm.compat.forge.jei.FurnitureCategory.setRecipe(FurnitureCategory.java:23) ~[paladin-furniture-mod-1.1.4-forge-mc1.19.4.jar%23197!/:?] {re:classloading}
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.19.4-forge-13.1.0.11.jar%23190!/:13.1.0.11] {re:classloading}
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:115) ~[jei-1.19.4-forge-13.1.0.11.jar%23190!/:13.1.0.11] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] {}
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:121) ~[jei-1.19.4-forge-13.1.0.11.jar%23190!/:13.1.0.11] {re:classloading}
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:103) ~[jei-1.19.4-forge-13.1.0.11.jar%23190!/:13.1.0.11] {re:classloading}
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.19.4-forge-13.1.0.11.jar%23190!/:13.1.0.11] {re:classloading}
	at com.unlikepaladin.pfm.compat.forge.jei.PaladinFurnitureModJEIPlugin.registerRecipes(PaladinFurnitureModJEIPlugin.java:53) ~[paladin-furniture-mod-1.1.4-forge-mc1.19.4.jar%23197!/:?] {re:classloading}
```
Mannaged to track the exception
