### ISSUE TITLE
Fabric 1.20.1 RC2 crashes on server start :/

### ISSUE THREAD

**Issue by MetaForge** [UnlikePaladin/paladin-furniture-mod#60]
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pfm'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at com.unlikepaladin.pfm.registry.fabric.ScreenHandlerRegistryImpl.getStoveMenuFactory(ScreenHandlerRegistryImpl.java:30) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.registry.ScreenHandlerRegistry.getStoveMenuFactory(ScreenHandlerRegistry.java) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.registry.ScreenHandlerRegistry.registerScreenHandlers(ScreenHandlerRegistry.java:20) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.registry.fabric.ScreenHandlerRegistryFabric.registerScreenHandlers(ScreenHandlerRegistryFabric.java:12) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.fabric.PaladinFurnitureModFabric.onInitialize(PaladinFurnitureModFabric.java:83) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.unlikepaladin.pfm.registry.fabric.ScreenHandlerRegistryImpl.getStoveMenuFactory(ScreenHandlerRegistryImpl.java:30) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.registry.ScreenHandlerRegistry.getStoveMenuFactory(ScreenHandlerRegistry.java) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.registry.ScreenHandlerRegistry.registerScreenHandlers(ScreenHandlerRegistry.java:20) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.registry.fabric.ScreenHandlerRegistryFabric.registerScreenHandlers(ScreenHandlerRegistryFabric.java:12) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at com.unlikepaladin.pfm.fabric.PaladinFurnitureModFabric.onInitialize(PaladinFurnitureModFabric.java:83) ~[paladin-furniture-mod-1.2.0-rc2-fabric-mc1.20.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more

**Comment by UnlikePaladin** [comment]
This was fixed in RC3
