### ISSUE TITLE
Fabric 1.19.2 Server Crash on Mod Version 1.2

### ISSUE THREAD

**Issue by rorysdonovan** [UnlikePaladin/paladin-furniture-mod#67]
Work's just fine with mod Ver. 1.1.1, not sure what's causing this.

Here is my console log:
13.11 18:10:37 [Multicraft] Starting server!
13.11 18:10:38 [Multicraft] Updating eula.txt file
13.11 18:10:39 [Server] INFO 3805b21d8a39b1afc195b2caa0a3c9a2317e9ed4e7a37135fef532473ddc3686
13.11 18:10:41 [Server] INFO Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
13.11 18:10:41 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
13.11 18:10:41 [Server] INFO [Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
13.11 18:10:41 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
13.11 18:10:41 [Server] main/INFO Loading Minecraft 1.19.2 with Fabric Loader 0.14.24
13.11 18:10:41 [Server] ForkJoinPool-1-worker-3/WARN The mod "extra_classes_origins" contains invalid entries in its mod json:
13.11 18:10:41 [Server] INFO - Unsupported root entry "pack_format" at line 15 column 18
13.11 18:10:41 [Server] ForkJoinPool-1-worker-1/WARN Mod magic_origins uses the version v0.3.5 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v0'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
13.11 18:10:41 [Server] ForkJoinPool-1-worker-1/WARN The mod "moreorigins" contains invalid entries in its mod json:
13.11 18:10:41 [Server] INFO - Unsupported root entry "pack_format" at line 15 column 18
13.11 18:10:42 [Server] ForkJoinPool-1-worker-1/WARN Mod gravestones uses the version v1.13 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
13.11 18:10:42 [Server] ForkJoinPool-1-worker-4/WARN Mod letmedespawn uses the version fabric-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
13.11 18:10:42 [Server] ForkJoinPool-1-worker-4/WARN Mod medievalorigins uses the version 1.19.x-4.1.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'x'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
13.11 18:10:42 [Server] ForkJoinPool-1-worker-1/WARN Mod mcwroofs uses the version 2.2.4b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '4b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
13.11 18:10:42 [Server] main/ERROR Incompatible mods found!
13.11 18:10:42 [Server] INFO net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:147) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:147) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:214) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:191) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO ... 4 more
13.11 18:10:42 [Server] INFO Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [/mods/paladin-furniture-mod-1.2.0-fabric-mc1.19.jar]: java.util.zip.ZipException: zip END header not found
13.11 18:10:42 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
13.11 18:10:42 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
13.11 18:10:42 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
13.11 18:10:42 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
13.11 18:10:42 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:214) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:191) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO ... 4 more
13.11 18:10:42 [Server] INFO Caused by: java.lang.RuntimeException: Error analyzing [/mods/paladin-furniture-mod-1.2.0-fabric-mc1.19.jar]: java.util.zip.ZipException: zip END header not found
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
13.11 18:10:42 [Server] INFO Caused by: java.util.zip.ZipException: zip END header not found
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1633) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile$Source.get(ZipFile.java:1441) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:195) ~[?:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.14.24.jar:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
13.11 18:10:42 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
13.11 18:10:45 [Multicraft] Server shut down (starting)
13.11 18:10:45 [Multicraft] Restarting crashed server in 300 seconds
13.11 18:10:45 [Multicraft] Server stopped

**Comment by rorysdonovan** [comment]
Ignore this, I figured it out. Apologies, lack of sleep lol
