### ISSUE TITLE
Mohist incompatibility 

### ISSUE THREAD

**Issue by FoxesVenom** [UnlikePaladin/paladin-furniture-mod#93]
Error message: Error loading class: vectorwing/farmersdelight/common/block/entity/CookingPotBlockEntity

Farmers delight is not currently installed and does not support 1.20.2 yet

Full Crash below

**07.01 22:26:11 [Server] WARN Error loading class: vectorwing/farmersdelight/common/block/entity/CookingPotBlockEntity (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity)
07.01 22:26:12 [Server] FATAL Mixin apply failed pfm.mixins.json:PFMMinecraftServerMixin -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on createReload could not find any targets matching 'lambda$reloadResources$23' in net.minecraft.server.MinecraftServer. Using refmap paladin-furniture-mod-forge-refmap.json [PREINJECT Applicator Phase -> pfm.mixins.json:PFMMinecraftServerMixin -> Prepare Injections ->  -> handler$zzp000$createReload(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]**
07.01 22:26:12 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on createReload could not find any targets matching 'lambda$reloadResources$23' in net.minecraft.server.MinecraftServer. **Using refmap paladin-furniture-mod-forge-refmap.json** [PREINJECT Applicator Phase -> pfm.mixins.json:PFMMinecraftServerMixin -> Prepare Injections ->  -> handler$zzp000$createReload(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2392!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142) ~[modlauncher-10.1.1.jar%2383!/:10.1.1]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:75) ~[modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107) ~[modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:37) ~[modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:455) ~[securemodules-2.2.3-mohist.jar:?]
07.01 22:26:12 [Server] INFO at net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:375) ~[securemodules-2.2.3-mohist.jar:?]
07.01 22:26:12 [Server] INFO at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:392) ~[securemodules-2.2.3-mohist.jar:?]
07.01 22:26:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3502) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.Class.getMethodsRecursive(Class.java:3643) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.Class.getMethod0(Class.java:3629) ~[?:?]
07.01 22:26:12 [Server] INFO at java.lang.Class.getMethod(Class.java:2319) ~[?:?]
07.01 22:26:12 [Server] INFO at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:95) ~[fmlloader-1.20.2-48.1.0.jar%23128!/:?]
07.01 22:26:12 [Server] INFO at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar%23128!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) [modlauncher-10.1.1.jar%2383!/:?]
07.01 22:26:12 [Server] INFO at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) [bootstrap-1.2.0.jar:?]
07.01 22:26:12 [Server] INFO at com.mohistmc.MohistMCStart.main(MohistMCStart.java:106) [custom-java20.jar:1.20.2-130]
07.01 22:26:12 [Server] INFO Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/minecraft/server/MinecraftServer
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:96)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10)
07.01 22:26:12 [Server] INFO at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126)
07.01 22:26:12 [Server] INFO at com.mohistmc.MohistMCStart.main(MohistMCStart.java:106)
07.01 22:26:12 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/MinecraftServer
07.01 22:26:12 [Server] INFO at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
07.01 22:26:12 [Server] INFO at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3502)
07.01 22:26:12 [Server] INFO at java.base/java.lang.Class.getMethodsRecursive(Class.java:3643)
07.01 22:26:12 [Server] INFO at java.base/java.lang.Class.getMethod0(Class.java:3629)
07.01 22:26:12 [Server] INFO at java.base/java.lang.Class.getMethod(Class.java:2319)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:95)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82)
07.01 22:26:12 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17)
07.01 22:26:12 [Server] INFO ... 8 more
07.01 22:26:12 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
07.01 22:26:12 [Server] INFO at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:412)
07.01 22:26:12 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
07.01 22:26:12 [Server] INFO ... 16 more
07.01 22:26:13 [Multicraft] Server shut down (starting)
07.01 22:26:13 [Multicraft] Restarting crashed server in 10 seconds
07.01 22:26:13 [Multicraft] Looks like a crash, check the server console. Return value: 1
07.01 22:26:13 [Multicraft] Server stopped

**Comment by UnlikePaladin** [comment]
that error is actually a warning, it crashed for a different reason, a mixin failed to apply, will investigate it

**Comment by UnlikePaladin** [comment]
Oh, you're using Mohist, it is unsupported atm I'm afraid but I'll see what I can do
